name: 'Grcov Covdir Report'
description: 'Generate a report from grcov-generated covdir output'
author: 'Peter Nehrer <pnehrer@eclipticalsoftware.com>'
inputs:
  file:
    description: 'Path to covdir.json file'
    default: './target/covdir.json'
  summary:
    description: 'Write report to step summary if `true`'
    default: 'false'
  out:
    description: 'Write report to the given file'
  title:
    description: 'Report title'
    default: 'Line coverage'
  # inputs for the bundled grcov
  skip_grcov:
    description: 'Skip bundled grcov and use a pre-generated covdir.json file instead'
    default: 'false'
  coverage_path:
    description: 'Path to coverage data for the bundled grcov'
    default: './target/coverage'
  source_dir:
    description: 'Source directory for grcov (-s flag)'
    default: '.'
  binary_path:
    description: 'Binary path for grcov (--binary-path flag)'
    default: './target/debug'
  keep_only:
    description: 'Keep only files matching pattern (--keep-only flag)'
    default: 'src/**'
  excl_start:
    description: 'Exclude start pattern (--excl-start flag)'
    default: '^mod\s+tests?\s*\{$'
  branch:
    description: 'Include branch coverage (--branch flag)'
    default: 'true'
  grcov_args:
    description: 'Additional arguments to pass to grcov'
outputs:
  lines_covered:
    description: 'Number of lines covered'
  lines_missed:
    description: 'Number of lines missed'
  lines_total:
    description: 'Total number of lines'
  coverage_percent:
    description: 'Percentage of lines covered'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    # grcov uses tempfile crate which needs a writable temp directory;
    # GitHub Actions mounts RUNNER_TEMP at /github/runner_temp
    TMPDIR: /github/runner_temp
  args:
    - "--file=${{ inputs.file }}"
    - "--summary=${{ inputs.summary }}"
    - "--title=${{ inputs.title }}"
    - "--out=${{ inputs.out }}"
    - "--skip-grcov=${{ inputs.skip_grcov }}"
    - "--coverage-path=${{ inputs.coverage_path }}"
    - "--source-dir=${{ inputs.source_dir }}"
    - "--binary-path=${{ inputs.binary_path }}"
    - "--keep-only=${{ inputs.keep_only }}"
    - "--excl-start=${{ inputs.excl_start }}"
    - "--branch=${{ inputs.branch }}"
    - "--grcov-args=${{ inputs.grcov_args }}"
branding:
  icon: award
  color: blue
